services:
  - type: web
    name: cbz-crm
    runtime: python
    buildCommand: pip install -r requirements.txt && python setup_database.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
